/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestPW.java
 *
 * Created on Aug 25, 2012, 3:20:07 PM
 */

package zigbeetool;

/**
 *
 * @author I14746
 */
public class RequestPW extends java.awt.Dialog {

    /** Creates new form RequestPW */
    public RequestPW(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        passTxtField.setText("betaperl");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWrongPass = new javax.swing.JLabel();
        passTxtField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        validateBtn = new javax.swing.JButton();
        lblLoginToAdminMode = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setResizable(false);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(zigbeetool.ZigBeeToolApp.class).getContext().getResourceMap(RequestPW.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        lblWrongPass.setName("lblWrongPass"); // NOI18N

        passTxtField.setText(resourceMap.getString("passTxtField.text")); // NOI18N
        passTxtField.setName("passTxtField"); // NOI18N
        passTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTxtFieldFocusGained(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        validateBtn.setText(resourceMap.getString("validateBtn.text")); // NOI18N
        validateBtn.setName("validateBtn"); // NOI18N
        validateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateBtnActionPerformed(evt);
            }
        });

        lblLoginToAdminMode.setText(resourceMap.getString("lblLoginToAdminMode.text")); // NOI18N
        lblLoginToAdminMode.setName("lblLoginToAdminMode"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWrongPass, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(validateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLoginToAdminMode)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblLoginToAdminMode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void passTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTxtFieldFocusGained

        lblWrongPass.setIcon(null);
        lblWrongPass.setText("");
}//GEN-LAST:event_passTxtFieldFocusGained

    private void validateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateBtnActionPerformed
        // TODO add your handling code here:

        String pw = new String(passTxtField.getPassword());

        if(pw.compareTo("betapearl")==0) {
//            p.setProperty("Keep Logged", String.valueOf(jCheckBox1.isSelected()));
//            pse.advancedPropsSaver(p);
//            this.dispose();
            ZigBeeToolApp.getApplication().getView().jTabbedPane1.setVisible(true);
             ZigBeeToolApp.getApplication().getView().getFrame().setSize(ZigBeeToolApp.getApplication().getView().getFrame().getWidth(), ZigBeeToolApp.getApplication().getView().getFrame().getHeight()+ ZigBeeToolApp.getApplication().getView().jTabbedPane1.getHeight());
            ZigBeeToolApp.getApplication().getView().getFrame().pack();
             ZigBeeToolApp.getApplication().getView().getFrame().repaint();
             try {
                this.finalize();
                this.dispose();
            } catch (Throwable ex) {

            //    Logger.getLogger(RequestPW.class.getName()).log(Level.SEVERE, null, ex);
            }




        } else{
            if(pw.equals("")){
                lblWrongPass.setText("Please provide the password.");
//                Icon ic=ProdProgrammerApp.getApplication().getView().getres().getIcon("wrong.icon");
//                lblWrongPass.setIcon(ic);

                lblWrongPass.setVisible(true);

            } else
                sayInvalid();
        }

        //else sayInvalid();
}//GEN-LAST:event_validateBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RequestPW dialog = new RequestPW(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLoginToAdminMode;
    private javax.swing.JLabel lblWrongPass;
    private javax.swing.JPasswordField passTxtField;
    private javax.swing.JButton validateBtn;
    // End of variables declaration//GEN-END:variables

    private void sayInvalid() {
        lblWrongPass.setText("Invalid password.");
       // ImageIcon ic= new ImageIcon(getClass().getResource("resources/err.png").getPath());
      //  Icon ic=ProdProgrammerApp.getApplication().getView().getres().getIcon("wrong.icon");
       // lblWrongPass.setIcon(ic);

        lblWrongPass.setVisible(true);
    }

}
